### ISSUE TITLE
Add phasing information to report

### ISSUE THREAD

**Issue by Madelinehazel** [ccmbioinfo/crg2#207]
Add the phased genotype and haplotype block (PS format field in VCF, note that unphased variants are not associated with a PS ID) to small variant reports.  

Example from a phased VCF, where the variant belongs to haplotype block 11863:

chr1    14673   .       G       C       18.7    PASS    .       GT:GQ:DP:AD:VAF:PL:PS   0|1:11:10:2,8:0.8:18,0,11:11863

Note that relevant branches are:
crg2 branch [crg2-hg38-pacbio](https://github.com/ccmbioinfo/crg2/tree/crg2-hg38-pacbio) 

cre branch [hg38-pacbio](https://github.com/ccmbioinfo/cre/tree/hg38-pacbio)

**Comment by anjalijain22** [comment]
Closing this issue here as this will be addressed in the crg2-pacbio repo: https://github.com/ccmbioinfo/crg2-pacbio/issues/5
