### ISSUE TITLE
Set remove-duplicates to default to True

### ISSUE THREAD

**Issue by Madelinehazel** [ccmbioinfo/crg2#23]
Duplicate removal should be set to True by default in the[ config](https://github.com/ccmbioinfo/crg2/blob/047becb8434999306a5b5f91055ca8ae6f763b2d/config.yaml#L37)

Should this be renamed to mark-duplicates, since that is what the rule does?

**Comment by aarthi-mohan** [comment]
yes changing it to rule name sounds right
