### ISSUE TITLE
Accept mix of bams and fastqs

### ISSUE THREAD

**Issue by Madelinehazel** [ccmbioinfo/crg2#75]
At the moment, the pipeline will only accept one input type (i.e. either fastq or bam or cram, as specified in config.yaml). crg2 performs [fastq_prep or bamtofastq or cramtofastq](https://github.com/ccmbioinfo/crg2/blob/master/rules/mapping.smk#L2) depending on config["run"]["input"]. Ideally, we would like to be able to provide a mix of input types, and would not have to specify input type in the config.

**Comment by mike8115** [comment]
(Untested) Idea; Rewrite Nour's cramtofastq rule to handle all kinds of input. The rule definition can stay the same, but edit the wrapper script to figure out which actions to do.

**Comment by Madelinehazel** [comment]
As per @mike8115's comment: 

- remove cramtofastq, fastq_prep and bamtofastq steps, and replace with one rule (e.g. input_prep or just fastq_prep)
- rewrite the [cramtofastq wrapper ](https://github.com/ccmbioinfo/crg2/blob/master/wrappers/samtools/fastq/wrapper.py) to include logic that, based on the column contents of the units.tsv file for a sample, will convert cram to fastq, bam to fastq, or call crg2/scripts/fastq_prep.py. Note that crg2 currently uses bedtools bamtofastq to convert bam to fastq; let's switch this to [samtools fastq](http://www.htslib.org/doc/samtools-fasta.html) for consistency with cramtofastq.
